#!/usr/bin/env python3
"""
Analyze C-class revision statistics for BraTS validation predictions.

The script reads nnU-Net validation summary.json files, optional HD95 JSON files
generated by compute_brats_hd95.py, and optional GT/prediction NIfTI directories.
It is intended for:
  - C6: f3 case-level failure analysis
  - C7: paired significance tests
  - C8: fold-level mean/std verification
"""

import argparse
import csv
import json
import math
from pathlib import Path
from statistics import mean, stdev

import numpy as np


REGION_KEYS = {
    "WT": "(1, 2, 3)",
    "TC": "(2, 3)",
    "ET": "(3,)",
}


def case_name(path: str) -> str:
    return Path(path).name


def finite(value) -> float | None:
    if value is None:
        return None
    value = float(value)
    if math.isfinite(value):
        return value
    return None


def read_summary(path: Path, trainer: str, fold: int) -> list[dict]:
    with path.open("r") as f:
        data = json.load(f)

    rows = []
    for item in data.get("metric_per_case", []):
        metrics = item["metrics"]
        row = {
            "trainer": trainer,
            "fold": fold,
            "case": case_name(item["prediction_file"]),
        }
        dices = []
        for region, key in REGION_KEYS.items():
            dice = finite(metrics[key].get("Dice"))
            row[f"{region}_dice"] = dice
            if dice is not None:
                dices.append(dice)
        row["mean_dice"] = mean(dices) if dices else None
        rows.append(row)
    return rows


def read_hd95_json(path: Path) -> dict[str, dict]:
    if not path.exists():
        return {}
    with path.open("r") as f:
        data = json.load(f)
    out = {}
    for item in data.get("per_case", []):
        out[item["case"]] = item
    return out


def add_hd95(rows: list[dict], hd95_by_case: dict[str, dict]) -> None:
    for row in rows:
        item = hd95_by_case.get(row["case"], {})
        values = []
        for region in REGION_KEYS:
            value = finite(item.get(region))
            row[f"{region}_hd95"] = value
            if value is not None:
                values.append(value)
        row["mean_hd95"] = mean(values) if values else None


def safe_std(values: list[float]) -> float:
    return stdev(values) if len(values) > 1 else 0.0


def summarize(rows: list[dict], metric: str) -> list[dict]:
    grouped = {}
    for row in rows:
        grouped.setdefault(row["trainer"], {}).setdefault(row["fold"], []).append(row)

    out = []
    for trainer, by_fold in sorted(grouped.items()):
        fold_values = []
        for fold, fold_rows in sorted(by_fold.items()):
            values = [r[metric] for r in fold_rows if r.get(metric) is not None]
            if values:
                fold_values.append(mean(values))
        if fold_values:
            out.append({
                "trainer": trainer,
                "metric": metric,
                "folds": ",".join(str(f) for f in sorted(by_fold)),
                "mean": mean(fold_values),
                "std": safe_std(fold_values),
                "n_folds": len(fold_values),
            })
    return out


def paired_tests(rows: list[dict], baseline: str, ours: str, metric: str) -> dict:
    by_key = {}
    for row in rows:
        by_key.setdefault((row["fold"], row["case"]), {})[row["trainer"]] = row

    baseline_values = []
    ours_values = []
    for pair in by_key.values():
        b = pair.get(baseline, {}).get(metric)
        o = pair.get(ours, {}).get(metric)
        if b is not None and o is not None:
            baseline_values.append(float(b))
            ours_values.append(float(o))

    result = {
        "metric": metric,
        "baseline": baseline,
        "ours": ours,
        "n_pairs": len(baseline_values),
        "baseline_mean": mean(baseline_values) if baseline_values else None,
        "ours_mean": mean(ours_values) if ours_values else None,
        "mean_delta_ours_minus_baseline": (
            mean([o - b for b, o in zip(baseline_values, ours_values)]) if baseline_values else None
        ),
        "paired_t_p": None,
        "wilcoxon_p": None,
    }
    if len(baseline_values) < 2:
        return result

    try:
        from scipy.stats import ttest_rel, wilcoxon
        t_res = ttest_rel(ours_values, baseline_values, nan_policy="omit")
        result["paired_t_p"] = float(t_res.pvalue)
        try:
            w_res = wilcoxon(ours_values, baseline_values, zero_method="wilcox")
            result["wilcoxon_p"] = float(w_res.pvalue)
        except ValueError:
            result["wilcoxon_p"] = None
    except Exception as e:
        result["test_error"] = str(e)
    return result


def find_prediction(pred_root: Path, trainer: str, fold: int, case: str) -> Path | None:
    candidates = [
        pred_root / f"{trainer}__nnUNetPlans__3d_fullres" / f"fold_{fold}" / "validation" / case,
        pred_root / trainer / f"fold_{fold}" / "validation" / case,
    ]
    for path in candidates:
        if path.exists():
            return path
    return None


def maybe_load_nifti_stats(rows: list[dict], gt_dir: Path | None, pred_root: Path | None) -> None:
    if gt_dir is None and pred_root is None:
        return
    try:
        import nibabel as nib
    except Exception as e:
        print(f"NIfTI volume stats skipped: cannot import nibabel ({e})")
        return

    def volume_stats(path: Path) -> dict:
        arr = np.asarray(nib.load(str(path)).get_fdata(), dtype=np.int16)
        return {
            "WT_vox": int(np.isin(arr, (1, 2, 3)).sum()),
            "TC_vox": int(np.isin(arr, (2, 3)).sum()),
            "ET_vox": int((arr == 3).sum()),
        }

    gt_cache = {}
    pred_cache = {}
    for row in rows:
        case = row["case"]
        if gt_dir is not None:
            gt_path = gt_dir / case
            if gt_path.exists():
                gt_cache.setdefault(case, volume_stats(gt_path))
                for key, value in gt_cache[case].items():
                    row[f"gt_{key}"] = value

        if pred_root is not None:
            pred_path = find_prediction(pred_root, row["trainer"], row["fold"], case)
            if pred_path is not None:
                pred_cache.setdefault(str(pred_path), volume_stats(pred_path))
                for key, value in pred_cache[str(pred_path)].items():
                    row[f"pred_{key}"] = value


def write_csv(path: Path, rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    keys = sorted({k for row in rows for k in row.keys()})
    with path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=keys)
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--results-root", required=True)
    parser.add_argument("--trainers", nargs="+", required=True)
    parser.add_argument("--folds", nargs="+", type=int, default=[0, 1, 2, 3, 4])
    parser.add_argument("--baseline", default="nnUNetTrainerUMambaEnc_150epochs")
    parser.add_argument("--ours", default="nnUNetTrainerUMambaEncRTHD_StageAwareDecoder_SkipCalibration_150epochs")
    parser.add_argument("--plans", default="nnUNetPlans")
    parser.add_argument("--config", default="3d_fullres")
    parser.add_argument("--hd95-root", default=None, help="Directory containing TRAINER_foldN_hd95.json files")
    parser.add_argument("--gt-dir", default=None, help="Optional gt_segmentations directory for volume stats")
    parser.add_argument("--pred-root", default=None, help="Optional directory with TRAINER/fold_N/validation predictions")
    parser.add_argument("--csv", required=True)
    parser.add_argument("--json", required=True)
    args = parser.parse_args()

    results_root = Path(args.results_root)
    rows = []
    missing = []
    for trainer in args.trainers:
        for fold in args.folds:
            summary = results_root / f"{trainer}__{args.plans}__{args.config}" / f"fold_{fold}" / "validation" / "summary.json"
            if not summary.exists():
                missing.append(str(summary))
                continue
            fold_rows = read_summary(summary, trainer, fold)
            if args.hd95_root:
                hd95_path = Path(args.hd95_root) / f"{trainer}_fold{fold}_hd95.json"
                add_hd95(fold_rows, read_hd95_json(hd95_path))
            rows.extend(fold_rows)

    maybe_load_nifti_stats(
        rows,
        Path(args.gt_dir) if args.gt_dir else None,
        Path(args.pred_root) if args.pred_root else None,
    )

    write_csv(Path(args.csv), rows)

    metrics = ["mean_dice", "WT_dice", "TC_dice", "ET_dice", "mean_hd95", "WT_hd95", "TC_hd95", "ET_hd95"]
    summary = {
        "missing_summary_files": missing,
        "fold_mean_std": [item for metric in metrics for item in summarize(rows, metric)],
        "paired_tests": [paired_tests(rows, args.baseline, args.ours, metric) for metric in metrics],
    }
    Path(args.json).parent.mkdir(parents=True, exist_ok=True)
    with Path(args.json).open("w") as f:
        json.dump(summary, f, indent=2, ensure_ascii=False)

    print(f"Saved case CSV: {args.csv}")
    print(f"Saved summary JSON: {args.json}")
    if missing:
        print(f"Missing summary files: {len(missing)}")


if __name__ == "__main__":
    main()
